# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  a1: a1
  a2: a2
  a3: a3
  a4: a4
  secret_key_base: 93cfc4d8ace441ff8026acffc3fc432b723c9fbd7855576a3a6c913d015fb473c332c2162202a18fdafbb7a320d7a318c8ef94cd123a522d9bd63847616898a5

test:
  a1: a1
  a2: a2
  a3: a3
  a4: a4
  secret_key_base: 2a676f53a519b008f08189ef24d13030307abc4a6458abd0509c7779293651d40d5cf2c72c3cbf2da05822fda53e78aed006fa40811bcf8e992799c4ed2617c6

production:
  a1: <%= ENV["A1"] %>
  a2: <%= ENV["A2"] %>
  a3: <%= ENV["A3"] %>
  a4: <%= ENV["A4"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
